Repository khengyun/FFood-shop, pull requests merged in 2023-10, with the labels that each got.

#1 fix: fix username button alignment on maximized sidebar; add bold text for active tab buttons
  src/main/webapp/WEB-INF/jspf/admin/components/adminSidebar.jspf
  src/main/webapp/assets/css/theme.css
Labels: bug

#38 Resolve #31 with cart badge for number of added cart items
  src/main/webapp/WEB-INF/jspf/common/components/header.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/cart.jspf
Labels: enhancement, frontend

#37 Fix home page's low color contrast on some elements
  src/main/webapp/assets/css/theme.css
  src/main/webapp/index.jsp
Labels: bug, frontend

#40 update sql server for docker.
  .gitignore
  Dockerfile
  README.md
  docker-compose.yml
  image.png
  init-db.Dockerfile
  init-db.sh
  src/main/java/DBConnection/DBConnection.java
Labels: enhancement, backend

#43 fix conflict
  README.md
  src/main/webapp/WEB-INF/jspf/common/components/header.jspf
  src/main/webapp/index.jsp
Labels: bug

#45 fix validation login form
  src/main/webapp/assets/js/validateForm.js
Labels: bug

#46 fix forget password and cannot login
  src/main/java/Controllers/ChangePasswordController.java
  src/main/java/Controllers/LoginController.java
  src/main/webapp/WEB-INF/jspf/common/components/footer.jspf
  src/main/webapp/WEB-INF/jspf/common/components/header.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/changePassword.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/login.jspf
  src/main/webapp/assets/js/validateForm.js
Labels: bug

#48 add again badge and bg-primary80
  src/main/webapp/WEB-INF/jspf/common/components/header.jspf
  src/main/webapp/index.jsp
Labels: bug, frontend

#50 Update staff&promotion manager page
  .gitignore
  nb-configuration.xml
  pom.xml
  src/main/java/Controllers/AdminController.java
  src/main/java/DBConnection/DBConnection.java
  src/main/java/Models/Voucher.java
  src/main/webapp/WEB-INF/jspf/admin/components/addVoucher.jspf
  src/main/webapp/WEB-INF/jspf/admin/components/addadmin.jspf
  src/main/webapp/WEB-INF/jspf/admin/components/deleteVoucher.jspf
  src/main/webapp/WEB-INF/jspf/admin/components/updateAdmin.jspf
  src/main/webapp/WEB-INF/jspf/admin/components/updatevoucher.jspf
  src/main/webapp/WEB-INF/jspf/promotionManager/components/addVoucher.jspf
  src/main/webapp/WEB-INF/jspf/promotionManager/components/deleteVoucher.jspf
  src/main/webapp/WEB-INF/jspf/promotionManager/components/promotionManagerSidebar.jspf
  src/main/webapp/WEB-INF/jspf/promotionManager/components/updatevoucher.jspf
  src/main/webapp/WEB-INF/jspf/promotionManager/home.jspf
  src/main/webapp/WEB-INF/jspf/promotionManager/imports/dataTablesScript.jspf
  src/main/webapp/WEB-INF/jspf/promotionManager/imports/dataTablesStyle.jspf
  src/main/webapp/WEB-INF/jspf/staff/components/addFood.jspf
  src/main/webapp/WEB-INF/jspf/staff/components/deleteFood.jspf
  src/main/webapp/WEB-INF/jspf/staff/components/staffSidebar.jspf
  src/main/webapp/WEB-INF/jspf/staff/components/updateFood.jspf
  src/main/webapp/WEB-INF/jspf/staff/foods.jspf
  src/main/webapp/WEB-INF/jspf/staff/home.jspf
  src/main/webapp/WEB-INF/jspf/staff/imports/dataTablesScript.jspf
  src/main/webapp/WEB-INF/jspf/staff/imports/dataTablesStyle.jspf
  src/main/webapp/admin.jsp
  src/main/webapp/assets/js/admin.js
  src/main/webapp/index.jsp
  src/main/webapp/promotionManager.jsp
  src/main/webapp/staff.jsp
  src/main/webapp/vendors/DataTables/datatables.css
  src/main/webapp/vendors/DataTables/datatables.min.css
  src/main/webapp/vendors/jquery-validation-1.19.5/test/index.html
Labels: enhancement, frontend

#58 Update homepage and backend for admin voucher
  src/main/java/Controllers/AdminController.java
  src/main/java/DAOs/VoucherDAO.java
  src/main/java/Models/Voucher.java
  src/main/webapp/WEB-INF/jspf/admin/components/addVoucher.jspf
  src/main/webapp/WEB-INF/jspf/admin/components/updatevoucher.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/login.jspf
  src/main/webapp/admin.jsp
  src/main/webapp/assets/js/admin.js
  src/main/webapp/assets/js/dataTablesConfig.js
  src/main/webapp/assets/js/validateForm.js
  src/main/webapp/index.jsp
Labels: backend

#60 update option lang button on header
  src/main/webapp/WEB-INF/jspf/LangOption/langviewoption.jspf
  src/main/webapp/WEB-INF/jspf/common/components/header.jspf
Labels: documentation, enhancement, frontend

#66 Fix dashboard's Food & Drinks tab freezing the page by repeated clicks
  src/main/webapp/assets/js/dataTablesConfig.js
Labels: bug, frontend, very high priority, urgent

#63 Limit number of shown menu items, with a "Show more" button to expand said menu
  src/main/webapp/WEB-INF/jspf/common/components/footer.jspf
  src/main/webapp/WEB-INF/jspf/common/components/header.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/ctaOrderBanner.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/foodCategories.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/foodList.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/hero.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/login.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/orderInstructions.jspf
  src/main/webapp/assets/css/style.css
  src/main/webapp/assets/js/home.js
  src/main/webapp/index.jsp
Labels: enhancement, frontend, high priority

#68 fix: language button display
  src/main/webapp/WEB-INF/jspf/LangOption/langviewbutton.jspf
  src/main/webapp/WEB-INF/jspf/LangOption/langviewoption.jspf
  src/main/webapp/WEB-INF/jspf/common/components/header.jspf
Labels: documentation, enhancement, backend

#72 Fix and update some backend feature
  init/full.sql
  src/main/java/Controllers/LoginController.java
  src/main/webapp/WEB-INF/jspf/guest/components/cart.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/foodList.jspf
  src/main/webapp/assets/js/validateForm.js
Labels: enhancement, frontend, backend, high priority

#70 Replace markdown issue templates with YAML ones (+ input fields and dropdown menus)
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: enhancement

#74 Update backend for promotion manager page
  src/main/java/Controllers/LoginController.java
  src/main/java/Controllers/PromotionManagerController.java
  src/main/java/Controllers/StaffController.java
  src/main/java/Filters/AuthenticationFilter.java
  src/main/webapp/WEB-INF/jspf/guest/components/cart.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/ctaOrderBanner.jspf
  src/main/webapp/WEB-INF/jspf/promotionManager/components/addVoucher.jspf
  src/main/webapp/WEB-INF/jspf/promotionManager/components/deleteVoucher.jspf
  src/main/webapp/WEB-INF/jspf/promotionManager/components/promotionManagerSidebar.jspf
  src/main/webapp/WEB-INF/jspf/promotionManager/components/updatevoucher.jspf
  src/main/webapp/WEB-INF/jspf/promotionManager/home.jspf
  src/main/webapp/WEB-INF/jspf/promotionManager/imports/dataTablesScript.jspf
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/assets/js/promotionManager.js
  src/main/webapp/promotionManager.jsp
Labels: backend

#77 Add backend for staff
  src/main/java/Controllers/LoginController.java
  src/main/java/Controllers/StaffController.java
  src/main/java/Filters/AuthenticationFilter.java
  src/main/webapp/WEB-INF/jspf/staff/components/staffSidebar.jspf
  src/main/webapp/WEB-INF/jspf/staff/home.jspf
  src/main/webapp/WEB-INF/jspf/staff/imports/dataTablesScript.jspf
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/admin.jsp
  src/main/webapp/assets/js/staff.js
  src/main/webapp/staff.jsp
Labels: enhancement, backend

#79 Fix/dashboard/food management/cannot add food
  src/main/java/Controllers/AdminController.java
  src/main/java/Controllers/HomeController.java
  src/main/java/Controllers/StaffController.java
  src/main/java/DAOs/FoodDAO.java
  src/main/java/Models/Food.java
  src/main/webapp/WEB-INF/jspf/admin/components/addFood.jspf
  src/main/webapp/WEB-INF/jspf/admin/components/updateFood.jspf
  src/main/webapp/WEB-INF/jspf/admin/foods.jspf
  src/main/webapp/WEB-INF/jspf/staff/components/addFood.jspf
  src/main/webapp/WEB-INF/jspf/staff/components/deleteFood.jspf
  src/main/webapp/WEB-INF/jspf/staff/components/updateFood.jspf
  src/main/webapp/WEB-INF/jspf/staff/foods.jspf
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/assets/js/admin.js
  src/main/webapp/assets/js/dataTablesConfig.js
  src/main/webapp/assets/js/staff.js
  src/main/webapp/assets/js/validateForm.js
  src/main/webapp/staff.jsp
Labels: bug, backend

#81 fix bug cannot add new item to cart
  src/main/java/Controllers/AddToCartController.java
  src/main/java/DAOs/FoodDAO.java
  src/main/webapp/assets/js/home.js
Labels: bug, backend, very high priority

#84 update voucher for admin and staff
  init/full.sql
  src/main/java/Controllers/AdminController.java
  src/main/java/Controllers/PromotionManagerController.java
  src/main/java/DAOs/VoucherDAO.java
  src/main/java/Models/Voucher.java
  src/main/webapp/WEB-INF/jspf/admin/components/addVoucher.jspf
  src/main/webapp/WEB-INF/jspf/admin/components/updatevoucher.jspf
  src/main/webapp/WEB-INF/jspf/promotionManager/components/addVoucher.jspf
  src/main/webapp/WEB-INF/jspf/promotionManager/components/updatevoucher.jspf
  src/main/webapp/admin.jsp
  src/main/webapp/assets/js/admin.js
  src/main/webapp/assets/js/promotionManager.js
  src/main/webapp/assets/js/validateForm.js
  src/main/webapp/promotionManager.jsp
Labels: enhancement, backend

#86 fix bug for voucher and add more
  src/main/java/Controllers/AdminController.java
  src/main/java/DAOs/FoodDAO.java
  src/main/java/DAOs/VoucherDAO.java
  src/main/webapp/WEB-INF/jspf/admin/components/deleteVoucher.jspf
  src/main/webapp/WEB-INF/jspf/admin/components/updatevoucher.jspf
  src/main/webapp/WEB-INF/jspf/admin/voucher.jspf
  src/main/webapp/admin.jsp
  src/main/webapp/assets/js/admin.js
  src/main/webapp/assets/js/dataTablesConfig.js
Labels: bug, frontend, backend

#89 update for promotion manager
  src/main/java/Controllers/PromotionManagerController.java
  src/main/webapp/WEB-INF/jspf/admin/components/deleteVoucher.jspf
  src/main/webapp/WEB-INF/jspf/promotionManager/components/addVoucher.jspf
  src/main/webapp/WEB-INF/jspf/promotionManager/components/deleteVoucher.jspf
  src/main/webapp/WEB-INF/jspf/promotionManager/components/promotionManagerSidebar.jspf
  src/main/webapp/WEB-INF/jspf/promotionManager/components/updatevoucher.jspf
  src/main/webapp/assets/js/admin.js
  src/main/webapp/assets/js/promotionManager.js
  src/main/webapp/promotionManager.jsp
Labels: enhancement, frontend, backend

#91 Add backend for admin role
  src/main/java/Controllers/AdminController.java
  src/main/java/Controllers/PromotionManagerController.java
  src/main/java/DAOs/AccountDAO.java
  src/main/java/DAOs/FoodDAO.java
  src/main/java/DAOs/PromotionManagerDAO.java
  src/main/java/DAOs/StaffDAO.java
  src/main/java/Models/Account.java
  src/main/java/Models/PromotionManager.java
  src/main/java/Models/Role.java
  src/main/java/Models/Staff.java
  src/main/webapp/WEB-INF/jspf/admin/components/addRole.jspf
  src/main/webapp/WEB-INF/jspf/admin/components/addVoucher.jspf
  src/main/webapp/WEB-INF/jspf/admin/components/addadmin.jspf
  src/main/webapp/WEB-INF/jspf/admin/components/deleteRole.jspf
  src/main/webapp/WEB-INF/jspf/admin/components/updateAdmin.jspf
  src/main/webapp/WEB-INF/jspf/admin/components/updateRole.jspf
  src/main/webapp/WEB-INF/jspf/admin/roles.jspf
  src/main/webapp/WEB-INF/jspf/promotionManager/components/addVoucher.jspf
  src/main/webapp/admin.jsp
  src/main/webapp/assets/js/admin.js
  src/main/webapp/assets/js/dataTablesConfig.js
  src/main/webapp/assets/js/promotionManager.js
  src/main/webapp/assets/js/validateForm.js
Labels: enhancement, frontend, backend, very high priority

#92 [update] : add new camera structure for dish prediction
  src/main/java/DBConnection/DBConnection.java
  src/main/webapp/WEB-INF/jspf/common/components/header.jspf
  src/main/webapp/WEB-INF/jspf/common/imports/resources.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/camera.jspf
  src/main/webapp/WEB-INF/jspf/hyperfeat/fooddetechbutton.jspf
  src/main/webapp/assets/js/lib/bower.json
  src/main/webapp/assets/js/lib/flash/Webcam.as
  src/main/webapp/assets/js/lib/flash/Webcam.fla
  src/main/webapp/assets/js/lib/flash/com/adobe/images/BitString.as
  src/main/webapp/assets/js/lib/flash/com/adobe/images/JPGEncoder.as
  src/main/webapp/assets/js/lib/flash/com/adobe/images/PNGEncoder.as
  src/main/webapp/assets/js/lib/flash/mx/utils/Base64Encoder.as
  src/main/webapp/assets/js/lib/webcam.js
  src/main/webapp/assets/js/lib/webcam.min.js
  src/main/webapp/assets/js/lib/webcam.swf
Labels: documentation, enhancement, frontend, backend

#93 Update notify for admin, staff, promotion manager dashboard
  src/main/java/Controllers/AdminController.java
  src/main/java/Controllers/EmailVerifyController.java
  src/main/java/Controllers/LoginController.java
  src/main/java/Controllers/PromotionManagerController.java
  src/main/java/Controllers/SignUpController.java
  src/main/java/Controllers/StaffController.java
  src/main/java/DAOs/VoucherDAO.java
  src/main/webapp/WEB-INF/jspf/admin/components/failure.jspf
  src/main/webapp/WEB-INF/jspf/admin/components/success.jspf
  src/main/webapp/WEB-INF/jspf/admin/imports/dataTablesScript.jspf
  src/main/webapp/WEB-INF/jspf/common/imports/resources.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/failure.jspf
  src/main/webapp/WEB-INF/jspf/promotionManager/components/failure.jspf
  src/main/webapp/WEB-INF/jspf/promotionManager/components/promotionManagerSidebar.jspf
  src/main/webapp/WEB-INF/jspf/promotionManager/components/success.jspf
  src/main/webapp/WEB-INF/jspf/promotionManager/imports/dataTablesScript.jspf
  src/main/webapp/WEB-INF/jspf/staff/components/failure.jspf
  src/main/webapp/WEB-INF/jspf/staff/components/staffSidebar.jspf
  src/main/webapp/WEB-INF/jspf/staff/components/success.jspf
  src/main/webapp/WEB-INF/jspf/staff/imports/dataTablesScript.jspf
  src/main/webapp/admin.jsp
  src/main/webapp/assets/js/adminNotify.js
  src/main/webapp/assets/js/home.js
  src/main/webapp/assets/js/promotionManagerNotify.js
  src/main/webapp/assets/js/staffNotify.js
  src/main/webapp/assets/js/userNotify.js
  src/main/webapp/index.jsp
  src/main/webapp/promotionManager.jsp
  src/main/webapp/staff.jsp
Labels: enhancement, frontend, backend

#95 update ai-feat
  src/main/webapp/WEB-INF/jspf/common/imports/resources.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/camera.jspf
Labels: bug, enhancement, backend

#94 Add mockup UI for Admin Dashboard Home
  src/main/webapp/WEB-INF/jspf/admin/components/chartDailyRevenueByFoodCategory.jspf
  src/main/webapp/WEB-INF/jspf/admin/components/chartMonthlyTarget.jspf
  src/main/webapp/WEB-INF/jspf/admin/components/chartRevenueByDay.jspf
  src/main/webapp/WEB-INF/jspf/admin/components/tableTopSellingFoods.jspf
  src/main/webapp/WEB-INF/jspf/admin/foods.jspf
  src/main/webapp/WEB-INF/jspf/admin/home.jspf
  src/main/webapp/WEB-INF/jspf/admin/imports/chartjs.jspf
  src/main/webapp/admin.jsp
  src/main/webapp/assets/css/style.css
  src/main/webapp/assets/js/dataTablesConfig.js
  src/main/webapp/package-lock.json
  src/main/webapp/package.json
  src/main/webapp/vendors/chart.umd.js
Labels: enhancement, frontend, very high priority

#97 update PSQL Server
  api/psqlserver/Dockerfile
  api/psqlserver/app.py
  api/psqlserver/config.py
  api/psqlserver/model/Food.py
  api/psqlserver/requirements.txt
  docker-compose.yml
Labels: documentation

#99 Fix some backend error
  init/full.sql
  src/main/java/Controllers/CheckoutController.java
  src/main/java/Controllers/SignUpController.java
  src/main/java/Controllers/UserController.java
  src/main/java/DAOs/AccountDAO.java
  src/main/java/DAOs/OrderDAO.java
  src/main/java/Models/Order.java
  src/main/webapp/WEB-INF/jspf/guest/components/failure.jspf
  src/main/webapp/assets/js/userNotify.js
  src/main/webapp/user.jsp
Labels: bug, high priority

#100 Update insight page
  src/main/java/Controllers/AdminController.java
  src/main/java/Models/MenuItem.java
  src/main/webapp/WEB-INF/jspf/admin/components/deleteUser.jspf
  src/main/webapp/WEB-INF/jspf/admin/insights.jspf
  src/main/webapp/WEB-INF/jspf/admin/users.jspf
  src/main/webapp/WEB-INF/jspf/admin/voucher.jspf
  src/main/webapp/WEB-INF/jspf/staff/orders.jspf
  src/main/webapp/admin.jsp
  src/main/webapp/assets/js/admin.js
  src/main/webapp/assets/js/dataTablesConfig.js
Labels: enhancement, frontend

#105 Update Cart modal UI + Fix Cart bugs
  src/main/java/Controllers/AddToCartController.java
  src/main/java/Controllers/CheckoutController.java
  src/main/java/Controllers/DeleteCartController.java
  src/main/webapp/WEB-INF/jspf/guest/components/cart.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/foodList.jspf
  src/main/webapp/assets/js/home.js
Labels: bug, enhancement, frontend, backend, high priority

#101 [update] delete cartItem not need to reload page
  src/main/java/Controllers/AddToCartController.java
  src/main/java/Controllers/DeleteCartController.java
  src/main/webapp/WEB-INF/jspf/common/components/footer.jspf
  src/main/webapp/WEB-INF/jspf/common/components/header.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/cart.jspf
  src/main/webapp/index.jsp
Labels: bug, enhancement, backend

#104 update qsql server
  api/psqlserver/app.py
  api/psqlserver/model/Food.py
  src/main/webapp/WEB-INF/jspf/admin/components/chartDailyRevenueByFoodCategory.jspf
  src/main/webapp/WEB-INF/jspf/admin/components/tableTopSellingFoods.jspf
  src/main/webapp/WEB-INF/jspf/admin/home.jspf
  src/main/webapp/WEB-INF/jspf/admin/imports/dataTablesScript.jspf
  src/main/webapp/WEB-INF/jspf/common/components/header.jspf
  src/main/webapp/WEB-INF/jspf/hyperfeat/fooddetechbutton.jspf
  src/main/webapp/assets/js/home.js
Labels: enhancement, frontend, backend, urgent

#108 Update with chart
  api/psqlserver/model/Food.py
  src/main/webapp/WEB-INF/jspf/admin/components/chartRevenueByDay.jspf
  src/main/webapp/WEB-INF/jspf/admin/components/todayview.jspf
  src/main/webapp/WEB-INF/jspf/admin/home.jspf
Labels: documentation, backend

#112 ]Update] admin backend for role tab and user tab of admin dashboard
  src/main/java/Controllers/AdminController.java
  src/main/java/DAOs/AccountDAO.java
  src/main/java/DAOs/CustomerDAO.java
  src/main/java/Models/Customer.java
  src/main/java/Models/User.java
  src/main/webapp/WEB-INF/jspf/admin/components/addUser.jspf
  src/main/webapp/WEB-INF/jspf/admin/components/deleteUser.jspf
  src/main/webapp/WEB-INF/jspf/admin/components/updateUser.jspf
  src/main/webapp/WEB-INF/jspf/admin/users.jspf
  src/main/webapp/admin.jsp
  src/main/webapp/assets/js/admin.js
  src/main/webapp/assets/js/dataTablesConfig.js
  src/main/webapp/assets/js/validateForm.js
Labels: enhancement, backend

#113 Fix some cart bug
  src/main/java/Controllers/CheckoutController.java
  src/main/java/Models/Food.java
  src/main/webapp/WEB-INF/jspf/guest/components/cart.jspf
  src/main/webapp/checkout.jsp
Labels: bug, backend

#114 fix: Restore cart modal UI to its former glory
  src/main/webapp/WEB-INF/jspf/guest/components/cart.jspf
Labels: bug, frontend, high priority

#110 [Update] update login with google feature
  api/psqlserver/app.py
  api/psqlserver/config.py
  api/psqlserver/model/Google_Auth.py
  api/psqlserver/requirements.txt
  src/main/webapp/WEB-INF/jspf/guest/components/login.jspf
  src/main/webapp/index.jsp
Labels: documentation, enhancement, backend, urgent

#120 Update apply using voucher for order food
  init/full.sql
  src/main/java/Controllers/AdminController.java
  src/main/java/Controllers/CheckoutController.java
  src/main/java/DAOs/VoucherDAO.java
  src/main/java/Models/Voucher.java
  src/main/webapp/WEB-INF/jspf/admin/roles.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/verify.jspf
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/assets/js/dataTablesConfig.js
  src/main/webapp/assets/js/validateForm.js
  src/main/webapp/checkout.jsp
  src/main/webapp/index.jsp
Labels: enhancement, backend
