Repository khengyun/FFood-shop, pull requests merged in 2023-11, with the labels that each got.

#123 update new database 131
  init/full.sql
  src/main/webapp/WEB-INF/jspf/guest/components/foodCategories.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/foodList.jspf
Labels: documentation, enhancement, backend

#124 Fix a lot of UI issues on Guest home page
  src/main/java/Controllers/HomeController.java
  src/main/webapp/WEB-INF/jspf/common/components/footer.jspf
  src/main/webapp/WEB-INF/jspf/common/components/header.jspf
  src/main/webapp/WEB-INF/jspf/common/imports/javascript.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/buttons/cartButton.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/buttons/googleSignInButton.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/buttons/googleSignUpButton.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/camera.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/cart.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/changePassword.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/ctaOrderBanner.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/foodCategories.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/foodList.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/forget.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/hero.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/login.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/signup.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/verify.jspf
  src/main/webapp/WEB-INF/jspf/hyperfeat/fooddetechbutton.jspf
  src/main/webapp/WEB-INF/jspf/hyperfeat/langviewbutton.jspf
  src/main/webapp/assets/css/style.css
  src/main/webapp/assets/css/theme.css
  src/main/webapp/assets/img/gallery/1.jpg
  src/main/webapp/assets/img/gallery/10.jpg
  src/main/webapp/assets/img/gallery/2.jpg
  src/main/webapp/assets/img/gallery/3.jpg
  src/main/webapp/assets/img/gallery/4.jpg
  src/main/webapp/assets/img/gallery/5.jpg
  src/main/webapp/assets/img/gallery/6.jpg
  src/main/webapp/assets/img/gallery/7.jpg
  src/main/webapp/assets/img/gallery/8.jpg
  src/main/webapp/assets/img/gallery/9.jpg
  src/main/webapp/assets/img/gallery/noodles.png
  src/main/webapp/assets/img/gallery/sub-sandwich.png
  src/main/webapp/assets/js/home.js
  src/main/webapp/index.jsp
Labels: bug, enhancement, frontend, very high priority, urgent

#126 Fix VN locale-related number formatting issues
  src/main/webapp/WEB-INF/jspf/common/imports/resources.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/cart.jspf
  src/main/webapp/admin.jsp
  src/main/webapp/checkout.jsp
  src/main/webapp/index.jsp
  src/main/webapp/promotionManager.jsp
  src/main/webapp/staff.jsp
  src/main/webapp/user.jsp
Labels: bug, frontend, medium priority

#130 Fix sections' not matching their siblings' height
  src/main/webapp/WEB-INF/jspf/admin/insights.jspf
Labels: bug, frontend, high priority

#128 Add Food Details modal for food cards
  src/main/java/Models/Cart.java
  src/main/webapp/WEB-INF/jspf/admin/foods.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/cart.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/foodCard.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/foodDetails.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/foodList.jspf
  src/main/webapp/admin.jsp
  src/main/webapp/assets/js/admin.js
Labels: enhancement, frontend, high priority

#122 [Feat] Add payment method
  api/Food_Classifier/src/predict.py
  api/psqlserver/app.py
  api/psqlserver/model/Food.py
  api/psqlserver/model/Order.py
  api/psqlserver/model/Payment.py
  api/psqlserver/model/vn_payment.py
  pom.xml
  src/main/java/Controllers/CheckoutController.java
  src/main/webapp/checkout.jsp
  src/main/webapp/user.jsp
Labels: documentation, enhancement, backend, very high priority

#132 Fix add to cart issues after merging branches
  src/main/java/Controllers/HomeController.java
  src/main/webapp/WEB-INF/jspf/common/components/footer.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/cart.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/foodDetails.jspf
  src/main/webapp/index.jsp
Labels: bug, frontend, backend, very high priority, urgent

#133 Fix/frontend/validate form
  src/main/webapp/WEB-INF/jspf/admin/users.jspf
  src/main/webapp/assets/css/style.css
  src/main/webapp/assets/css/theme.css
  src/main/webapp/assets/js/dataTablesConfig.js
  src/main/webapp/assets/js/validateForm.js
Labels: enhancement, frontend

#134 Fix Admin Dashboard's DataTables-related UI
  src/main/webapp/WEB-INF/jspf/admin/components/adminSidebar.jspf
  src/main/webapp/WEB-INF/jspf/admin/components/help.jspf
  src/main/webapp/WEB-INF/jspf/admin/foods.jspf
  src/main/webapp/WEB-INF/jspf/admin/history.jspf
  src/main/webapp/WEB-INF/jspf/admin/orders.jspf
  src/main/webapp/WEB-INF/jspf/admin/roles.jspf
  src/main/webapp/WEB-INF/jspf/admin/users.jspf
  src/main/webapp/WEB-INF/jspf/admin/voucher.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/buttons/googleSignInButton.jspf
  src/main/webapp/assets/css/theme.css
  src/main/webapp/assets/js/dataTablesConfig.js
  src/main/webapp/assets/js/validateForm.js
  src/main/webapp/user.jsp
Labels: bug, frontend, high priority

#135 Update some thing new for first release
  init/full.sql
  src/main/java/Controllers/AdminController.java
  src/main/java/Controllers/CheckoutController.java
  src/main/java/Controllers/HomeController.java
  src/main/java/DAOs/AccountDAO.java
  src/main/java/DailyTask/DailyTaskServlet.java
  src/main/java/Models/Account.java
  src/main/java/Models/User.java
  src/main/webapp/WEB-INF/jspf/admin/users.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/failure.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/foodDetails.jspf
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/assets/js/userNotify.js
  src/main/webapp/index.jsp
Labels: bug, enhancement, backend

#136 fix some wrong after merge
  init/full.sql
Labels: bug, backend, urgent

#137 Update New Logic Search Engine && Search By Drop
  api/psqlserver/model/Food.py
  src/main/webapp/WEB-INF/jspf/guest/components/camera.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/foodDetails.jspf
  src/main/webapp/WEB-INF/jspf/hyperfeat/fooddetechbutton.jspf
Labels: frontend, backend, high priority

#140 update something before release
  api/psqlserver/model/Food.py
  api/psqlserver/requirements.txt
  init/full.sql
  src/main/java/Controllers/AdminController.java
  src/main/java/Controllers/CheckoutController.java
  src/main/java/Controllers/PromotionManagerController.java
  src/main/java/Controllers/StaffController.java
  src/main/java/DAOs/FoodDAO.java
  src/main/java/DAOs/OrderDAO.java
  src/main/java/Models/Cart.java
  src/main/java/Models/Food.java
  src/main/java/Models/Order.java
  src/main/webapp/WEB-INF/jspf/admin/components/addFood.jspf
  src/main/webapp/WEB-INF/jspf/admin/components/adminSidebar.jspf
  src/main/webapp/WEB-INF/jspf/admin/components/history.jspf
  src/main/webapp/WEB-INF/jspf/admin/components/success.jspf
  src/main/webapp/WEB-INF/jspf/admin/components/updateFood.jspf
  src/main/webapp/WEB-INF/jspf/admin/components/updateOrder.jspf
  src/main/webapp/WEB-INF/jspf/admin/components/updateRole.jspf
  src/main/webapp/WEB-INF/jspf/admin/foods.jspf
  src/main/webapp/WEB-INF/jspf/admin/history.jspf
  src/main/webapp/WEB-INF/jspf/admin/orders.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/cart.jspf
  src/main/webapp/WEB-INF/jspf/promotionManager/foods.jspf
  src/main/webapp/WEB-INF/jspf/staff/components/addFood.jspf
  src/main/webapp/WEB-INF/jspf/staff/components/updateFood.jspf
  src/main/webapp/WEB-INF/jspf/staff/foods.jspf
  src/main/webapp/WEB-INF/jspf/staff/orders.jspf
  src/main/webapp/admin.jsp
  src/main/webapp/assets/js/admin.js
  src/main/webapp/assets/js/adminNotify.js
  src/main/webapp/assets/js/dataTablesConfig.js
  src/main/webapp/assets/js/staff.js
  src/main/webapp/assets/js/userNotify.js
  src/main/webapp/assets/js/validateForm.js
Labels: bug, enhancement, backend, urgent

#144 Update maximum quantity per cart item
  src/main/java/Models/Cart.java
  src/main/webapp/WEB-INF/jspf/guest/components/cart.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/foodCard.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/foodDetails.jspf
Labels: enhancement, frontend, medium priority

#145 Update search by keyword UI and behavior
  api/psqlserver/model/Food.py
  src/main/webapp/WEB-INF/jspf/common/components/footer.jspf
  src/main/webapp/WEB-INF/jspf/common/components/header.jspf
  src/main/webapp/WEB-INF/jspf/hyperfeat/fooddetechbutton.jspf
  src/main/webapp/assets/js/home.js
Labels: enhancement, frontend, high priority

#146 Fix error before release
  init/full.sql
  src/main/java/Controllers/StaffController.java
  src/main/java/Controllers/UserController.java
  src/main/java/Models/Account.java
  src/main/webapp/WEB-INF/jspf/admin/components/addFood.jspf
  src/main/webapp/WEB-INF/jspf/admin/components/chartRevenueByDay.jspf
  src/main/webapp/WEB-INF/jspf/admin/components/todayview.jspf
  src/main/webapp/WEB-INF/jspf/admin/components/updateFood.jspf
  src/main/webapp/WEB-INF/jspf/admin/components/updateOrder.jspf
  src/main/webapp/WEB-INF/jspf/admin/foods.jspf
  src/main/webapp/WEB-INF/jspf/admin/home.jspf
  src/main/webapp/WEB-INF/jspf/promotionManager/components/chartRevenueByDay.jspf
  src/main/webapp/WEB-INF/jspf/promotionManager/components/todayview.jspf
  src/main/webapp/WEB-INF/jspf/promotionManager/components/updateFood.jspf
  src/main/webapp/WEB-INF/jspf/promotionManager/foods.jspf
  src/main/webapp/WEB-INF/jspf/promotionManager/voucher.jspf
  src/main/webapp/WEB-INF/jspf/staff/components/addFood.jspf
  src/main/webapp/WEB-INF/jspf/staff/components/chartRevenueByDay.jspf
  src/main/webapp/WEB-INF/jspf/staff/components/todayview.jspf
  src/main/webapp/WEB-INF/jspf/staff/components/updateFood.jspf
  src/main/webapp/WEB-INF/jspf/staff/components/updateOrder.jspf
  src/main/webapp/WEB-INF/jspf/staff/foods.jspf
  src/main/webapp/WEB-INF/jspf/staff/orders.jspf
  src/main/webapp/assets/js/admin.js
  src/main/webapp/assets/js/dataTablesConfig.js
  src/main/webapp/assets/js/promotionManager.js
  src/main/webapp/assets/js/staff.js
  src/main/webapp/assets/js/validateForm.js
  src/main/webapp/checkout.jsp
  src/main/webapp/user.jsp
Labels: bug, frontend, backend, urgent

#147 Fix before release
  init/full.sql
  src/main/webapp/WEB-INF/jspf/common/components/header.jspf
  src/main/webapp/WEB-INF/jspf/common/components/header1.jspf
  src/main/webapp/WEB-INF/jspf/common/components/header2.jspf
  src/main/webapp/WEB-INF/jspf/staff/home.jspf
  src/main/webapp/checkout.jsp
  src/main/webapp/index.jsp
  src/main/webapp/user.jsp
Labels: bug, frontend

#152 Fix error before release v2
  src/main/java/Controllers/AdminController.java
  src/main/java/Controllers/CheckoutController.java
  src/main/java/Controllers/UserController.java
  src/main/java/DAOs/VoucherDAO.java
  src/main/webapp/WEB-INF/jspf/guest/components/cart.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/foodDetails.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/login.jspf
Labels: bug, frontend, backend, very high priority

#141 fix total_account not found
  api/Food_Classifier/src/predict.py
  api/psqlserver/model/Food.py
  api/psqlserver/requirements.txt
  src/main/java/DBConnection/DBConnection.java
  src/main/webapp/WEB-INF/jspf/admin/components/chartMonthlyTarget.jspf
  src/main/webapp/WEB-INF/jspf/admin/components/todayview.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/foodDetails.jspf
Labels: documentation, backend

#153 Update before release v3
  README.md
  cover.png
  image.png
  src/main/java/Controllers/LoginController.java
  src/main/java/Controllers/PromotionManagerController.java
  src/main/webapp/WEB-INF/jspf/admin/components/failure.jspf
  src/main/webapp/WEB-INF/jspf/admin/components/todayview.jspf
  src/main/webapp/WEB-INF/jspf/promotionManager/components/failure.jspf
  src/main/webapp/WEB-INF/jspf/promotionManager/components/todayview.jspf
  src/main/webapp/WEB-INF/jspf/staff/components/todayview.jspf
  src/main/webapp/assets/js/dataTablesConfig.js
  src/test/java/Controllers/LoginControllerTest.java
Labels: bug, enhancement, backend, urgent

#154 Update Release v2.0.1
  README.md
  api/Food_Classifier/src/predict.py
  api/psqlserver/model/Food.py
  api/psqlserver/requirements.txt
  cover.png
  docker-compose.yml
  image.png
  init/full.sql
  src/main/java/Controllers/AdminController.java
  src/main/java/Controllers/CheckoutController.java
  src/main/java/Controllers/LoginController.java
  src/main/java/Controllers/PromotionManagerController.java
  src/main/java/Controllers/SignUpController.java
  src/main/java/Controllers/StaffController.java
  src/main/java/Controllers/UserController.java
  src/main/java/DAOs/AccountDAO.java
  src/main/java/DAOs/VoucherDAO.java
  src/main/java/Validation/ValidationUtils.java
  src/main/webapp/WEB-INF/jspf/admin/components/chartMonthlyTarget.jspf
  src/main/webapp/WEB-INF/jspf/admin/components/failure.jspf
  src/main/webapp/WEB-INF/jspf/admin/components/todayview.jspf
  src/main/webapp/WEB-INF/jspf/common/components/header.jspf
  src/main/webapp/WEB-INF/jspf/common/components/header1.jspf
  src/main/webapp/WEB-INF/jspf/common/components/header2.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/cart.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/foodDetails.jspf
  src/main/webapp/WEB-INF/jspf/guest/components/login.jspf
  src/main/webapp/WEB-INF/jspf/promotionManager/components/failure.jspf
  src/main/webapp/WEB-INF/jspf/promotionManager/components/todayview.jspf
  src/main/webapp/WEB-INF/jspf/staff/components/todayview.jspf
  src/main/webapp/WEB-INF/jspf/staff/home.jspf
  src/main/webapp/assets/js/dataTablesConfig.js
  src/main/webapp/assets/js/home.js
  src/main/webapp/assets/js/validateForm.js
  src/main/webapp/checkout.jsp
  src/main/webapp/index.jsp
  src/main/webapp/user.jsp
  src/test/java/DAOs/FoodDAOIT.java
Labels: documentation, enhancement, frontend, backend

#156 Fix some error
  src/main/java/Controllers/CheckoutController.java
  src/main/webapp/checkout.jsp
Labels: bug, backend

#159 Add drag and drop UI + upload image UI
  src/main/webapp/WEB-INF/jspf/guest/components/camera.jspf
  src/main/webapp/WEB-INF/jspf/hyperfeat/fooddetechbutton.jspf
  src/main/webapp/index.jsp
Labels: enhancement, frontend, high priority, urgent

#158 Fix error before present
  src/main/webapp/assets/js/dataTablesConfig.js
  src/main/webapp/assets/js/validateForm.js
Labels: bug, backend

#161 update setenv.sh for client timezone
  Dockerfile
  setenv.sh
Labels: bug, documentation, backend

#164 Update README.md
  README.md
Labels: documentation, enhancement
